In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
    --------------------------------------- 0.3/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 707.1 kB/s eta 0:00:17
   - -------------------------------------- 0.5/12.5 MB 707.1 kB/s eta 0:00:17
   -- ------------------------------------- 0.8/12.5 MB 650.5 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/12.5 MB 749.4 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/12.5 MB 781.6 kB/s eta 0:00:15
   ---- ----------------------------------- 1.3/12.5 MB 781.6 kB/s eta 0:00:15
   ----- ---------------------------------- 1.6/12.5 MB 811.5 kB/s eta 0:00:14
   ----- ---------------------------------- 1.8/12.5 MB 819.3 kB/s eta 0:00:13
   ------ --------


[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [5]:
a=np.array(9)
print(a)
print(type(a))
print(a.ndim)

9
<class 'numpy.ndarray'>
0


In [6]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [7]:
c=np.array([[1,2,3,4],[5,6,7,8]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [8]:
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(d)
print(type(d))
print(d.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
<class 'numpy.ndarray'>
3


In [9]:
#list vs array
a=[1,2,3,4]
b=[5,6,7,8]
print(a+b)#merge values and prints two lists in one list

[1, 2, 3, 4, 5, 6, 7, 8]


In [10]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)#adds values of both arrays in same position of arrays

[ 6  8 10 12]


In [11]:
#sum
e=sum(a)
print(e)
print(np.sum(c+d))

10
208


In [12]:
#mean
print(np.mean(c+d))

13.0
